import { Poppins, Lato } from "next/font/google";
import "./globals.css";

// Configure Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // Specify the weights you need
  variable: "--font-poppins", // Define a CSS variable for Poppins
});

// Configure Lato
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
  variable: "--font-lato", // Define a CSS variable for Lato
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}